### ISSUE TITLE
kakurenbo 0.2.2とpaper_trail 3.0.6でエラーとなる

### ISSUE THREAD

**Issue by umey111** [alfa-jpn/kakurenbo#19]
いつも便利に使用させて頂いております。
paper_trailのバージョンアップにより、kakurenboでエラーとなるようです。
paper_trailが3.0.3時はエラーとならないようです。
確認お願いできますと幸いです。

バージョンは以下となります。
activerecord 4.1.4
paper_trail 3.0.6
kakurenbo 0.2.2

以下ログになります。
```ruby
/project/vendor/bundle/ruby/2.0.0/gems/kakurenbo-0.2.2/lib/kakurenbo/mixin_ar_base.rb:28:in `remove_instance_variable': instance variable @table_name not defined (NameError)
	from /project/vendor/bundle/ruby/2.0.0/gems/kakurenbo-0.2.2/lib/kakurenbo/mixin_ar_base.rb:28:in `block in inherited'
	from /project/vendor/bundle/ruby/2.0.0/gems/kakurenbo-0.2.2/lib/kakurenbo/mixin_ar_base.rb:24:in `instance_eval'
	from /project/vendor/bundle/ruby/2.0.0/gems/kakurenbo-0.2.2/lib/kakurenbo/mixin_ar_base.rb:24:in `inherited'
	from /project/vendor/bundle/ruby/2.0.0/gems/paper_trail-3.0.6/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:4:in `<module:PaperTrail>'
	from /project/vendor/bundle/ruby/2.0.0/gems/paper_trail-3.0.6/lib/paper_trail/frameworks/active_record/models/paper_trail/version.rb:3:in `<top (required)>'
```

**Comment by alfa-jpn** [comment]
詳細なご報告有り難うございます。
該当箇所の修正を `fix/paper_trail ` ブランチにて行いました。
お手数ですがご確認いただければ幸いです。

**Comment by umey111** [comment]
修正ありがとうございます。
確認したところ無事動きました。
ありがとうございます。
